### ISSUE TITLE
[feature] Replace a line during inject

### ISSUE THREAD

**Issue by Whoaa512** [jondot/hygen#84]
Amazing piece of software you've got here. Has saved my team countless hours.

I'd like the ability to be able to run an arbitrary function on the matching line and return a modified version of that line.

**Comment by jondot** [comment]
Thanks!
Interesting.. what can help is if you drop here a sample for a template with API you would expect, and then i'll do the hard work of implementing that. so just pencil in how you would see the YAML frontmatter for such an ability

**Comment by Whoaa512** [comment]
So I've thought about this a bit and I keep coming back to 2 API proposals.

Both share the common boolean attribute `replace` to trigger the replacement code.

The tricky part comes in specifying the replacement function. My initial thought is to specify a `replacer` attribute which contains the path to a js file with a single export or maybe a specifically named export. Alternatively we could try allowing the replacement function to be defined within the body of the template.

Defining the function in the template body is convenient for simple replacements, but we are then forced to eval the body which doesn't seem desirable.

Here's an example:

```yaml
---
replace: true
to: src/apis/serverless.yml
at_line: 145
skip_if: "<%= h.inflection.classify(name) %>,"
eof_last: false
replacer: ./replacers/my-replacement-func.js
---
// Some body text here
// Or maybe a replacement function
```

What do you think @jondot?
